### ISSUE TITLE
cannot install even with sudo

### ISSUE THREAD

**Issue by monkeywithacupcake** [opencollective/opencollective-setup#2]
`npm install -g opencollective-setup` fails on permissions
`sudo npm install -g opencollective-setup` fails on not being able to find a file `ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/opencollective-setup/dist/bin/opencollective-setup.js'
`
I have attached logs of both. 
[2019-03-02T16_40_43_345Z-debug.log](https://github.com/opencollective/opencollective-setup/files/2922305/2019-03-02T16_40_43_345Z-debug.log)
[2019-03-02T16_41_47_846Z-debug.log](https://github.com/opencollective/opencollective-setup/files/2922306/2019-03-02T16_41_47_846Z-debug.log)

Please advise

**Comment by znarf** [comment]
I don't know, it works here. Try to `rm -rf /usr/local/lib/node_modules/opencollective-setup` and try again?

**Comment by znarf** [comment]
@monkeywithacupcake then try `ls /usr/local/lib/node_modules/opencollective-setup/dist/bin` and if it's not existing, figure which directory is missing.

**Comment by monkeywithacupcake** [comment]
I deleted the old one and recloned. All is well!
