### ISSUE TITLE
BUG：Unable to open your README.md file

### ISSUE THREAD

**Issue by willin** [opencollective/opencollective-setup#3]
```bash
npm install -g opencollective-setup
opencollective-setup -r willin/leader.js.cool -i
```

Log:

```
Forking willin/leader.js.cool

? Enter the slug of your collective (https://opencollective.com/:slug) willin
? Update CONTRIBUTING.md? No
? Update .github/ISSUE_TEMPLATE.md? Yes
? Update .github/PULL_REQUEST_TEMPLATE.md? No
> Unable to open your README.md file
```

**Comment by znarf** [comment]
@willin try again?

If it's not working you should inspect the ` /tmp/leader.js.cool`directory.

**Comment by willin** [comment]
it's an empty fold with nothing in it.

**Comment by trustin** [comment]
I did a little bit of debugging about this, and found that it failed to fork a repository to `opencollective` org:

```json
{
    url: 'https://api.github.com/repos/line/armeria/forks?org=opencollective',
    status: 403,
    statusText: 'Forbidden',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
}
```

We need to check the result of the fork operation here: https://github.com/opencollective/opencollective-setup/blob/master/src/commands/setup.js#L136

Anyways, do you have an idea about why a fork operation fails? I specified my personal access token with `repo` permission granted. The repository I'm trying to fork (`line/armeria`) is a public repository of an organization I belong to.

**Comment by znarf** [comment]
You should try without the GitHub token and commit the result manually to your repository.
