### ISSUE TITLE
Issue with -r setup with multiple same name repos

### ISSUE THREAD

**Issue by monkeywithacupcake** [opencollective/opencollective-setup#8]
If you use the -r setup and type `org/repo` the local updates will be rejected because there already exists an `opencollective/repo` of the same name and when the program creates the new repo, it names it `opencollective/repo-1` or `repo-2`. 
Example that I saw today was for Optimus. 

Two potential solutions
1) Change the setup code to hold whatever `opencollective/repo[-1]` that is created and use that when pushing updates and making the PR
2) Change the setup code to create `opencollective/[slug]` since the slugs have to be unique

**Comment by znarf** [comment]
@monkeywithacupcake can you provide a real world example?

**Comment by monkeywithacupcake** [comment]
Yes, the example that brought this up for me was when using the repo jenssegers/optimus when there already existed an opencollective for ironmussa/optimus -> the opencollective repo could not be opencollective/optimus
![Screen Shot 2019-07-14 at 17 48 16](https://user-images.githubusercontent.com/7316730/61191439-9a291b80-a65f-11e9-822f-395de64bd817.png)

**Comment by monkeywithacupcake** [comment]
Did you have an idea of how to address @znarf ? I'm not sure of the best approach with the current structure of slugs, but we might be able to say, 'if there are more than one....then get the one with the biggest number at the end?'

**Comment by znarf** [comment]
I think we should delete all these forks once the PR is merged or closed.

That way, less chances to run into duplicates.

**Comment by monkeywithacupcake** [comment]
Okay. I am willing to delete after merge/close. I can go back and delete the hundreds that we have.

**Comment by piamancini** [comment]
@monkeywithacupcake just added a bunch of new ones. Sorry it's been so long. I'll try and do this more often.

**Comment by monkeywithacupcake** [comment]
I'm going to consider this closed since we found a masking tape solution with deleting our repo forks.
